// Re-export all types from the central definition
export type {
  ProjectMeta,
  LayerType,
  PlaybackMode,
  PlaybackConfig,
  Page,
  Project,
  Layer,
  BaseTransform,
  CanvasItem,
  EffectTrack,
  ItemTransform,
  EffectPlugin,
  AnimationPreset,
  AssetType,
  AssetEntry,
  AssetFolder,
  GenerationCategory,
  AgentProfile,
  GenerationRequest,
  GenerationStatus,
  GenerationResult,
  ExportConfig,
} from './project'
